name: 'matrix-builder'
description: 'Get all changed files from event and create a json object for use as a job matrix'
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
inputs:
  token:
    description: github token for api requests
    required: true
    default: ${{github.token}}
  config_path:
    description: path in repo to check for matrix configuration files, string in the form of repo path
    required: true
    default: '.*'
  file_type:
    description: filename to identify a directory as a build context
    required: true
    default: main.ts
outputs:
  all:
    description: Array of all changed files
