name: action test

on:
  pull_request:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: jaredzieche/matrix-builder@feature/test
        with:
          config_path: 'src/.*'
