name: action test

on:
  pull_request:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jaredzieche/matrix-builder@feature/test
        id: matrix-step
        with:
          config_path: 'test/test.*'
          file_type: 'Dockerfile'
          map_file: 'test/map.json'

      - run: |
          echo ${{ fromJSON(steps.matrix-step.outputs.matrix) }}


